apiVersion: apps/v1
kind: Deployment
metadata:
  name: authenticus-4-sea
spec:
  replicas: 5
  selector:
    matchLabels:
      app: authenticus-4-sea
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: authenticus-4-sea
    spec:
      containers:
        - image: html-server-image:v4
          name: authenticus-4-sea
          imagePullPolicy: Never
          ports:
            - containerPort: 80
      restartPolicy: Always




      